### PR TITLE
radix64, fiestel round, small domain, MIT License, test and coverage fix

### PR DESCRIPTION
**Pull request by PuspenduBanerjee**
Added radix64, fiestel round, small domain, MIT License

### CODE REVIEW

**Comment by PuspenduBanerjee** [comment]
@maresb reopened this pull request after addressing suggestions.

**Comment by maresb** [comment]
Thanks @PuspenduBanerjee! Just a reminder, since I'm not a maintainer I can't approve your changes. For that we'll have to wait for @bschoening, and his opinions could be different from mine.

Adding the `.idea` to the `.gitignore` file doesn't remove the corresponding files. Since this is a crypto library, it's important for the Git history to be clean so that all modifications are easy to audit. There are two ways I know of how to remove the files from the Git history:
1. Perform a `git rebase` and rewrite the history, for example by squashing all commits.
2. Make a fresh clone, copy the changes, and commit them there.
Unfortunately these are both rather painful, and will require a force-push afterwards.

Regarding the `setup.py` I opened #6. In the meantime, I see that your CI is dependent on it for the `pip install .` command. (The `-e` flag is unnecessary here.) In that case I think it would be better to use instead @bschoening's version of `setup.py` from PyPI which can be extracted from the `.tar.gz` archive [here](https://pypi.org/project/ff3/#files).

Regarding the license change, I don't think I've ever seen a contributor adding a different license before. I'm curious how @bschoening will react.

It might be easier if you divide this massive pull request into several different independent PRs. For example, I'd probably do something like
1. Changes to the main code to add new features, with corresponding documentation in the README.
2. Request to add or switch to the MIT license.
3. Update tests and CI, adding `setup.py` from PyPI.

The advantage to doing it in smaller pieces is that it makes it easier to review. If one PR takes longer to review, then the other parts can be merged in the meantime.

**Comment by maresb** [comment]
This is a bit awkward regarding the PyPI repositories...

@bschoening's https://pypi.org/project/ff3/
@PuspenduBanerjee's https://pypi.org/project/pyFPE/

Having two PyPI packages for the same thing is quite unfortunate, as this will be confusing for users. Why would @bschoening want to switch from his own PyPI package to @PuspenduBanerjee's as proposed in this PR?

Also, the `.idea/` files are still cluttering up the history as can be seen from here:
  https://github.com/PuspenduBanerjee/python-fpe/commits
I just realized that another easier solution to this would be if @bschoening were to merge this PR with the "Squash and merge" option by clicking the triangle on the right side of the merge button and selecting "Squash and merge". See screenshot:
image

**Comment by PuspenduBanerjee** [comment]
Why another package?

- As the seup.py was missing in original repo, I was not aware of the binary distro.
- The other package is for doing other FPEs, not only FF3x.

**Comment by bschoening** [comment]
Regarding other FPE's, only FF1 and FF3 have been approved by NIST for format preserving encryption. FF1 has patent claims on it and I'm told by the patent owners that includes open source implementations.

**Comment by bschoening** [comment]
"below 19 rounds cipher is breakable" vs 8 for NIST, do you have a reference for this comment?

**Comment by PuspenduBanerjee** [comment]
> "below 19 rounds cipher is breakable" vs 8 for NIST, do you have a reference for this comment?

https://eprint.iacr.org/2020/1311.pdf
In context of allowing small domain see the paper, page#18 "The second option, increasing the number of rounds, is, in our opinion, the better option of the two. This means that for FF1 and FF3-1 the number of rounds should be at least 18 (if we want to allow for 20-bit words)"

**Pull request closed without merging**
