### PR TITLE
Restore test_minlen_maxlen

### PR DESCRIPTION
**Pull request by maresb**

### CODE REVIEW

**Comment by bschoening** [comment]
Both Intel, AMD and ARM implement the IEEE floating point standard.  The calculations are deterministic.   As stated in the below "The IEEE-754 standard is the reference for almost all modern computer floating-point mathematics implementations, including ARM floating-point systems".  
https://developer.arm.com/documentation/den0042/a/Floating-Point/Floating-point-basics-and-the-IEEE-754-standard

Granted, floating point representation is inherently inexact within epsilon.

The test should run exactly the same on every platform w/IEEE floating point, right?

**Comment by maresb** [comment]
> The test should run exactly the same on every platform w/IEEE floating point, right?

That's a very strong statement. I'm no expert on floating-point arithmetic and the corresponding caveats. What you're saying seems plausible, but I can't be really sure without sinking hours into the question.

In Python, you don't specify whether the floats are double, quad, etc. It seems like Python chooses double for you in the current implementation. Numpy offers more numerical types. If for some reason the precision changes (e.g. from double to single due to some funny non-CPython implementation of Python) then this check should be rerun.

On my computer, this test runs in less than 1ms. In the 20 minutes I spent trying to find a quick answer to your question and writing up this comment, this test could have been run over 1 million times...

Do you have any particular objection to including this test? I always thought that this is exactly the sort of thing one should write test cases for.

In case you're offended by running this test each time and losing that 1ms, I also included a commented-out decorator `@unittest.skip("This test is basically static.")` to skip the test. That way you could disable it (but why?) until there's some particular reason to run it.

**Comment by bschoening** [comment]
I didn't mean to come across too strongly. I'm not worried at all about the run-time of the test, but rather its usefulness and whether the additional code added to unit tests is beneficial/necessary.  Writing maintainable unit test is my objective.  As Einstein remarked, 'Everything should be made as simple as possible, but no simpler.'

Interesting about the double type, I looked it up and Python's 'float' type is the same length as a double in other programming languages, which is an IEEE double. 

Here is another blurb about IEEE floating point from an article in Computer Survey.  

"The IEEE standard goes further than just requiring the use of a guard digit. It gives an algorithm for addition, subtraction, multiplication, division and square root, and requires that implementations produce the same result as that algorithm. Thus, when a program is moved from one machine to another, the results of the basic operations will be the same in every bit if both machines support the IEEE standard. This greatly simplifies the porting of programs."

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by bschoening** [comment]
minLen is tied to Domain size and is a fuzzy number which is an approximation because small domains were found vulnerable to attach by Hoang, Tessaro, and Trieu,.  In the revised spec, they increased the minimum domain from 100 to 1M. 

Q: I suppose you could get around this by just using a Decimal

from decimal import Decimal, Context, ROUND_UP
ctx = Context(prec=2)
ctx.divide(Decimal('1000000.00').log10(ctx), Decimal('10.00').log10(ctx)).quantize(Decimal('1.'), rounding=ROUND_UP)

**Comment by bschoening** [comment]
Happened across this discussion of the issue which suggests adding epsilon...
https://newbedev.com/how-do-you-calculate-log-base-2-in-java-for-integers

**Pull request closed without merging**
